### ISSUE TITLE
Check out poster

### ISSUE THREAD

**Issue by JJ** [geneura-papers/2016-ea-languages-PPSN#22]
Published here https://docs.google.com/presentation/d/1XhuA43O4eD1TG-IoHitV1Azh9iD6tpMYnNWmkfX8bLA/edit?usp=sharing

Will take to print tomorrow.

**Comment by mariosky** [comment]
Ok, I was in charge of printing something? I'm on my way today.
Tomorrow I could print it if you have any problems

**Comment by JJ** [comment]
Don't worry, we can print it in the print shop near the conference site.

Have a great trip!

**Comment by pacastillo** [comment]
have a good time in Evo*
   :)
