### ISSUE TITLE
Adding new stuff to send the paper to EvoStar

### ISSUE THREAD

**Issue by vrivas** [geneura-papers/2016-ea-languages-PPSN#9]
According to conclusions yielded today (in Geneura weekly meeting), we are going to modify this paper to send new advances in this topic to EvoStar.
So, we have to decide:
- What could we add?
- How could we modify the initial sections in order to avoid plagiarism?
- Which conference will be the selected to send the paper?
### About EvoStar

EvoStar 2017 will be held from 9am on Wednesday 19 April until 2pm on Friday 21 April, with an optional Friday afternoon local excursion. 
### Important Dates
- Submission Deadline: <s>1 November 2016</s> **15 November 2016**
- Notification: 9 January 2017
- Camera-ready: 25 January 2017
- Mandatory registration per paper: 1 February 2017
- Student bursary deadline: 15 February 2017
- Early registration discount: 1 March 2017
- Registration deadline: 10 April 2017
- EvoStar dates: 19-21 April 2017

**Comment by JJ** [comment]
It will probably be pushed back 10 days or so. .

**Comment by JJ** [comment]
Working on it now. Please @M42 @mariosky @iblancasa see if you can lend a hand adding new languages or updating what's in there.

**Comment by iblancasa** [comment]
@JJ ACK

**Comment by mroman42** [comment]
@JJ I have updated the Haskell code adding comments and explaining the data structure it uses in #17.
